project_name: nelm-source-controller

builds:
  - skip: true

release:
  extra_files:
    - glob: config/release/*.yaml
  prerelease: "auto"
  header: |
    ## Changelog

    [{{.Tag}} changelog](https://github.com/werf/{{.ProjectName}}/blob/{{.Tag}}/CHANGELOG.md)
  footer: |
    ## Container images

    - `registry.werf.io/nelm/source-controller:{{.Tag}}`

    Supported architectures: `linux/amd64`, `linux/arm64` and `linux/arm/v7`.

changelog:
  disable: true

checksum:
  extra_files:
    - glob: config/release/*.yaml

source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source_code"
